export{default as Buttons} from "./buttons/buttons";
export{default as Carousel} from "./carousel/carousel";
export{default as functioncard} from "./functionCard/function"
export{default as Infoprofile} from "./infoProfile/infoprofile"
export{default as MainCointainer} from "../screens/main"
export{default as Nav} from "./nav/nav"
export{default as Feed} from "./FeedProfile/FeedProfile"
export{default as Landing} from "./Landing/landing"
export{default as LogIn} from "./SignIn/Signin"
export{default as SignUp} from "./SignUp/signup"
export{default as Upload} from "./uploadd/upload"